### ISSUE TITLE
Custom Zend\Db\Adapter\Adapter factory doesn't work.

### ISSUE THREAD

**Issue by vbogoev** [zendframework/zend-db#188] opened 2016-11-10 18:19 UTC
Hello,

I have some trouble with custom created factory for Zend\Db\Adapter\Adapter. I installed Skeleton Application + Zend\Db. I configured everything as usual but this is what happened.

In my global/local.php I have

`'service_manager' => array(
        'factories' => array(
            'Zend\Db\Adapter\Adapter' => 'Database\Adapter\Factory\MainAdapterFactory',
        ),
    ),`

The problem is that the code never go to `"Database\Adapter\Factory\MainAdapterFactory"`, but instead go directly to `"Zend\Db\Adapter\AdapterServiceFactory"`. I have only that settings for db and I thing it's some sort of bug. In ZF2 this code works as expected.

**Comment by alextech** [comment] 2016-11-11 05:49
Could not reproduce. I created a class 
```
namespace Portal\Service;

class MainAdapterFactory implements FactoryInterface {
    public function __invoke(ContainerInterface $container, $requestedName, array $options = null) {
        return new Pdo(new Connection());
    }
}
```

with factory definition copied from yours. Then I called `$db = $container->get('Zend\Db\Adapter\Adapter');` from controller factory.

Could your factory not been updating to ZF3 style? is local.php being loaded in?

**Comment by vbogoev** [comment] 2016-11-11 10:38
When you called `$db = $container->get('Zend\Db\Adapter\Adapter');` do you check what instance is returned? My factory is ZF3 style, otherwise it will give me error, in my opinion. And yes local.php is loaded.

This is my factory:

    <?php

    namespace Database\Adapter\Factory;

    use Zend\ServiceManager\Factory\FactoryInterface;
    use Interop\Container\ContainerInterface;
    use Zend\Db\Adapter\AdapterServiceFactory;
    use Zend\Db\TableGateway\Feature\GlobalAdapterFeature as GlobalAdapterFeature;

    class MainAdapterFactory implements FactoryInterface {
    
        public function __invoke(ContainerInterface $container, $requestedName, array $options = null){
            die('Please die...');

            $adapter = new AdapterServiceFactory($container, $requestedName);
            GlobalAdapterFeature::setStaticAdapter($adapter);

            return $adapter;
        }

    }

This is my final config:

    'service_manager' => 
        array (size=5)
          'aliases' => 
               array (size=11)
                 ...
                 'Zend\Db\Adapter\Adapter' => string 'Zend\Db\Adapter\AdapterInterface' (length=32)
                 ...
          'factories' => 
               array (size=19)
                 ...
                 'Zend\Db\Adapter\AdapterInterface' => string 'Zend\Db\Adapter\AdapterServiceFactory' (length=37)
                 ...
              'Zend\Db\Adapter\Adapter' => string 'Database\Adapter\Factory\MainAdapterFactory' (length=43)
          'abstract_factories' => 
               array (size=3)
                 ...
                 1 => string 'Zend\Db\Adapter\AdapterAbstractServiceFactory' (length=45)
                 ...
       ...

I don't know from where it comes alias `'Zend\Db\Adapter\Adapter' => 'Zend\Db\Adapter\AdapterInterface'` maybe from ServiceManager class. Whatever. When I call `$container->get('Zend\Db\Adapter\Adapter')` my custom factory never executes(execution never "die").

**Comment by alextech** [comment] 2016-11-11 14:07
Thanks for that service_manager dump. Gave me a hint where to look and I could reproduce it when I load `Zend\Db` to `modules` key in  `application.config.php`. This loads `zend-db/src/Module.php` (in vendor directory) which in turn merges `zend-db/src/ConfigProvider.php`. It loads this module for convenience in new apps so your 'db' key in configuration can be picked up by the factory right away without more work. But if you want your own factory, you do not want that module loader getting in the way, so after you enabled Zend\Db through skeleton or composer, remove it from list of modules to load. Not loading module does not mean you won't be able to use it, just that the conflicting ConfigProvider will not be merged in.

**Comment by vbogoev** [comment] 2016-11-11 14:23
Thanks for the quick response. I tried that too but when I remove `Zend\Db` from `modules.config.php` I get this error: 

> "Fatal error: Uncaught exception 'Zend\ServiceManager\Exception\ServiceNotFoundException' with message 'Unable to resolve service "Zend\Db\Adapter\Adapter" to a factory; are you certain you provided it during configuration?'"

My local.php is:

    'db' => array(
        'driver' => 'Pdo',
        'dsn' => 'mysql:dbname=framework;host=localhost',
        'username' => 'root',
        'password' => '',
        'driver_options' => array(
            PDO::MYSQL_ATTR_INIT_COMMAND => 'SET NAMES \'UTF8\''
        ),
    ),
    'service_manager' => array(
        'factories' => array(
            'Zend\Db\Adapter\Adapter' => 'Database\Adapter\Factory\MainAdapterFactory',
        ),
        'display_exceptions' => true,
    ),

I think it's ok but can't figure out why ServiceManager throw that error...

**Comment by alextech** [comment] 2016-11-11 14:44
Its better than a conflict, some progress, but not sure why not resolving it. When I debug this type of problem, I put a breakpoint at the `->get('ServiceName')` and Step Into every line to see what final class name servicemanager ends up loading, to watch how it assembles it. I would also not use hardcoded class names in strings. SM may not reliably resolve those. Current best practice is `'Zend\Db\Adapter\Adapter' => MainAdapterFactory::class` (or Database\Adapter\Factory\MainAdapterFactory::class if want to stay using full name). That often takes out mistakes of inaccurately guessing how composer autoloader will see the class. Sorry, for vague response this time.

**Comment by vbogoev** [comment] 2016-11-12 19:27
I'm still stuck and can't fix this issue... I followed the trace and I think the poblem is somewhere in `vendor\composer\ClassLoader.php -> findFileWithExtension` function. If you see this function there's one if statement:

        $logicalPathPsr4 = strtr($class, '\\', DIRECTORY_SEPARATOR) . $ext;

        $first = $class[0];
        if (isset($this->prefixLengthsPsr4[$first])) {

And in my case with `Database\Adapter\Factory\MainAdapterFactory` I have

`$logicalPathPsr4 = 'Database\Adapter\Factory\MainAdapterFactory.php'`
`$first = 'D'`

and $this->prefixLengthsPsr4 which is `array('Z'..., 'I'..., 'A'...)` but no 'D' as a key. I think this is the place where the file must be returned... 

So, I moved my file `MainAdapterFactory` to `vendor\zendframework\zend-db\src\Adapter\` and it works(because in `$this->prefixLengthsPsr4` there's a 'Z' key with 'Zend\Db' in it). 

Am I doing something wrong with composer(I'm still newbie with working with composer) or there's something else I didn't do?

**Comment by froschdesign** [comment] 2017-02-04 20:54
This is not a `zend-db` problem.

@vbogoev 
> In ZF3 as I see it's without "Module Name" folder in src.

The explanation can be found in the migration guide: "[Migration - Application: Autoloading](https://docs.zendframework.com/tutorials/migration/to-v3/application/#autoloading)"

**Closed by froschdesign** 2017-02-04 20:54 UTC
Labels: invalid
